#+TITLE: Readme
#+AUTHOR: Nathan Davis

* Introduction
  This repository contains my personal emacs configuration.
  I'm making this available in the hopes that others will find it useful.
  You may wish to take bits and pieces for your own configuration.
  I've tried to make it fairly modular, in order to make it easier
  to do that.

  If you have improvements or additions you'd like to share,
  I'd be interested in hearing from you.
* Usage
  To incorporate this repository into your own emacs setup,
  you simply need to include [[file:init.el][init.el]] in your emacs config.
  Note that =init.el= currently assumes the repository
  is located at =~/emacs=,
  because I had problems with loading reliably using relative paths
  with the =load= function.
  If you place the repository in a different location,
  you will need to update the paths to reflect the new location.

  You may wish to comment out features to don't want.
* Structure
  The repository follows a simple structure:
  1. [[file:init.el][init.el]] is the "master" file which loads everything
  2. [[file:package-utils.el][package-utils.el]] defines a =package-utils/conditonally-install-packages=
     function.
     This function takes a list of package names,
     and installs any packages in the list that are not already installed.
  3. [[file:repositories.el][repositories.el]] specifies which package repositories will be consulted
     in order to satisfy dependencies.
     You may with to alter this list to suite your needs.
  4. The remaining files setup specific features:
     - [[file:color-theme.el][color-theme.el]] defines the color theme I use,
       as well as a few view-related functions that I rarely use.
     - [[file:clojure-init.el][clojure-init.el]] ensures packages used
       for clojure/clojurescript development are installed.
     - [[file:slime-init.el][slime-init.el]] configures slime integration for Common Lisp development.
     - [[file:paredit.el][paredit.el]] enables paredit mode by default for various lisp major modes.
     - [[file:misc.el][misc.el]] contains miscellaneous configuration tweaks.
